project_id = "sngrwurunaidqbhzcsrv"

[functions.create-contact-voice]
verify_jwt = false

[functions.process-voice-unified]
verify_jwt = false

[functions.process-voice-edit]
verify_jwt = false

[functions.process-patient-note]
verify_jwt = false

[functions.manage-patient-session]
verify_jwt = false

[functions.create-user]
verify_jwt = false
